name: ci

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      hive-metastore:
        image: ghcr.io/criccomini/hive-metastore-standalone:latest
        ports:
          - 9083:9083

    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2

    - name: Build using Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install pdm
        pdm install

    - name: Run black
      run: |
        source venv/bin/activate
        pdm run black --check --diff pymetastore/ tests/

    - name: Run isort
      run: |
        source venv/bin/activate
        pdm run isort pymetastore/ tests --check-only --diff

    - name: Run pylint
      run: |
        source venv/bin/activate
        pdm run pylint pymetastore/ tests/

    - name: Run pyright
      run: |
        source venv/bin/activate
        pdm run pyright

    - name: Run unit tests
      run: |
        source venv/bin/activate
        pdm run pytest tests/unit

    - name: Run integration tests
      run: |
        source venv/bin/activate
        pdm run pytest tests/integration
